### PR TITLE
Update SessionCacher to remove race in test

### PR DESCRIPTION
**Pull request by jacobhaven**
r? @maxtaco

### CODE REVIEW

**Comment by jacobhaven** [comment]
@akalin-keybase I also added a bit of code to prevent the goroutine leak you pointed out.

**Comment by akalin-keybase** [comment]
cool thanks!

**Comment by maxtaco** [comment]
Thanks @jacobhaven, this looks pretty good, is there any way to get test coverage on the cleaning of the queue?  Otherwise, we could have a memleak.

**Comment by jacobhaven** [comment]
@maxtaco: Updated with your suggestions.

**Comment by maxtaco** [comment]
Very clean, let me try to break it one last time!

**Comment by maxtaco** [comment]
:+1:

**Pull request merged**
