### PR TITLE
Initialize syncCh in server

### PR DESCRIPTION
**Pull request by jacobhaven**
I found a bug in the sync code while testing with the `gregorcli` tool. I don't think this is the only one, however. The server seems to crash after a `incoming.sync` RPC call.

@oconnor663 Logging around the RPC and Server code would be immensely helpful.

r? @maxtaco  @patrickxb

### CODE REVIEW

**Comment by jacobhaven** [comment]
gregorcli output:
```
[D] {tcp://10.0.1.117:4443} New connection
[D] {tcp://10.0.1.117:4443} call(0): method=gregor.1.auth.authenticateSessionToken; err=null; arg=[{"session":"<snip>"}];
[D] {tcp://10.0.1.117:4443} reply(0): method=gregor.1.auth.authenticateSessionToken; err=null; res={"uid":"JpS0RkKgaD0yGtP4165fAA==","sid":"a652ed02c379412eb6ee4b6a390af902"};
[P] {tcp://10.0.1.117:4443} call gregor.1.auth.authenticateSessionToken ran in 9ms
[D] {tcp://10.0.1.117:4443} call(1): method=gregor.1.incoming.ping; err=null; arg=[{}];
[D] {tcp://10.0.1.117:4443} reply(1): method=gregor.1.incoming.ping; err=null; res="pong";
[P] {tcp://10.0.1.117:4443} call gregor.1.incoming.ping ran in 0ms
[D] {tcp://10.0.1.117:4443} call(2): method=gregor.1.incoming.consumeMessage; err=null; arg=[{"m":{"ibm":{"stateUpdate":{"md":{"uid":"JpS0RkKgaD0yGtP4165fAA==","msgID":"ruU+/26tn9eBvf/nrkOIHw==","ctime":1461254945519,"deviceID":"ZmFrZWRldmlkMTIzNDU2Nw==","inBandMsgType":1},"creation":{"category":"foo","dtime":{"time":0,"offset":0},"notifyTimes":null,"body":"ZmFrZSBib2R5"}}}}}];
[D] {tcp://10.0.1.117:4443} reply(2): method=gregor.1.incoming.consumeMessage; err=null; res=null;
[P] {tcp://10.0.1.117:4443} call gregor.1.incoming.consumeMessage ran in 34ms
[D] {tcp://10.0.1.117:4443} call(3): method=gregor.1.incoming.sync; err=null; arg=[{"uid":"JpS0RkKgaD0yGtP4165fAA==","deviceid":"ZmFrZWRldmlkMTIzNDU2Nw==","ctime":1101254945554}];
[D] {tcp://10.0.1.117:4443} serve(0): method=gregor.1.outgoing.broadcastMessage; err=null; arg=[{"m":{"ibm":{"stateUpdate":{"md":{"uid":"JpS0RkKgaD0yGtP4165fAA==","msgID":"ruU+/26tn9eBvf/nrkOIHw==","ctime":1461254945519,"deviceID":"ZmFrZWRldmlkMTIzNDU2Nw==","inBandMsgType":1},"creation":{"category":"foo","dtime":{"time":0,"offset":0},"notifyTimes":null,"body":"ZmFrZSBib2R5"}}}}}];
received message: gregor1.DeviceID{0x66, 0x61, 0x6b, 0x65, 0x64, 0x65, 0x76, 0x69, 0x64, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37}
[P] {tcp://10.0.1.117:4443} serve gregor.1.outgoing.broadcastMessage ran in 0ms
[D] {tcp://10.0.1.117:4443} reply(0): method=gregor.1.outgoing.broadcastMessage; err=null; res=null;
[D] {tcp://10.0.1.117:4443} EOF
[P] {tcp://10.0.1.117:4443} call gregor.1.incoming.sync ran in 32ms
2016/04/21 16:09:05 EOF
```
At this point, the docker container exits and the server goes offline until ECS restarts it. @aalness Maybe looking at the docker logs on the server would help?

**Comment by patrickxb** [comment]
LGTM

**Comment by oconnor663** [comment]
oh my god, selecting on a nil channel deadlocks?

**Comment by jacobhaven** [comment]
I'm merging this because it solves one issue. There's still some other problem going on with the sync code. I think I'll add a lot of logging and see what comes up.

**Comment by akalin-keybase** [comment]
@oconnor663 yeah, that's by design: http://dave.cheney.net/2014/03/19/channel-axioms

**Comment by maxtaco** [comment]
Any ideas why this bug wasn't caught in the test site?

**Comment by oconnor663** [comment]
@akalin-keybase send to a closed channel panicks, but send to a nil channel _silently hangs forever_?!

**Pull request merged**
