### PR TITLE
Check if UID is nil in checkMessageAuth

### PR DESCRIPTION
**Pull request by jacobhaven**
r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
By my read, this is a security hole. It means I'm authenticated by default if it's a nil UID.

**Comment by jacobhaven** [comment]
Correct. Not a security hole though. A message with `nil` UID should be readable by anyone.

**Comment by maxtaco** [comment]
Let's be conservative here and reject any messages with a nil UID as unauthorized. We can loosen the restriction later if we decide we need it (I don't see any reasons now why we'd need it).

**Comment by maxtaco** [comment]
👍

**Pull request merged**
