### PR TITLE
make MYSQL_DSN errors clearer

### PR DESCRIPTION
**Pull request by oconnor663**
r? @jacobhaven

### CODE REVIEW

**Comment by jacobhaven** [comment]
I'd sort of prefer to create a `NewDSNGetter(*S3Config)` and move it out of the `bin` package to remove that test dependency.

**Comment by mmaxim** [comment]
My current PR does that @jacobhaven if you want to check out how I moved it out of bin into test. It was necessary since we had to vendor the storage directory into the client.

**Comment by maxtaco** [comment]
@mmaxim you might want to check out the C/I bug above, I think we have a flakey test  / race condition stemming from a PR you pushed last week.

**Comment by mmaxim** [comment]
@maxtaco this one?

=== RUN   TestLevelDBClient
[I] Sync failure: local state hash != server state hash

**Comment by maxtaco** [comment]
No that one is expected.  The close on end channel stack trace at the end of the C/I run. 

@patrickxb do you have any ideas about the lack of broadcast?

**Comment by patrickxb** [comment]
I don't know why the broadcast failed in TestPublish.

**Comment by mmaxim** [comment]
This is just a bug with one of the tests I recently added, basically a `ConsumeMessage` comes in after `Shutdown` gets called, which doesn't seem like something that can happen in normal operation. I'll fix the test.

**Comment by oconnor663** [comment]
@jacobhaven can I go ahead and land this?

**Comment by jacobhaven** [comment]
👍

**Pull request merged**
