### PR TITLE
rename server status table to gregor_server_status

### PR DESCRIPTION
**Pull request by maxtaco**
- also don't make it DATETIME(6) since that's not available on 5.5.49
  (which comes with LTS 14.04).

### CODE REVIEW

**Comment by maxtaco** [comment]
Just merging this to fix keybase/keybase C/I

**Comment by patrickxb** [comment]
We use DATETIME(6) in other places in gregor.

**Comment by maxtaco** [comment]
i know i've had to pull it out if running in CI

**Comment by maxtaco** [comment]
ok, let me back that back out, good point.  don't neeed it anyways if we create the tables manually in keybase.sql

**Comment by patrickxb** [comment]
Also, the reason it was `server_status` was so it could be used by any service, not just gregor.

**Comment by maxtaco** [comment]
oh ok, i can back this whole change out and workaround it a different way

**Comment by patrickxb** [comment]
if the name is too vague, i'm fine with another name, just would prefer if it didn't have `gregor` in it.  If we want to use it for `reminderd` for example.

**Pull request merged**
