### PR TITLE
Remove vendoring, add dummy authentication to gregord

### PR DESCRIPTION
**Pull request by patrickxb**
This adds dummy authentication to gregord.

Vendoring causing issues once keybase/go/client integration performed, so I removed it all.

Tried to vendor gregord only, but that also had issues.

So in the interest of moving forward, I just got rid of all the vendoring.

r? @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
@patrickxb  what's up with the C/I failure?

**Comment by maxtaco** [comment]
:+1:

**Comment by maxtaco** [comment]
(Is this project now mature enough that we have our first flakey C/I test?)

**Comment by patrickxb** [comment]
I don't know...the only thing I can think is that it has something to do with a vendored package?  Of course there's no way to tell which version travis is using...presumably the latest, but...

**Comment by maxtaco** [comment]
My money is on a race condition in the tests that only shows up when running on a slow system like CI. Your theory wouldn't explain why sometimes it works, and others not.  Well, let's scrutinize the logs the next time there's a failure.

**Comment by patrickxb** [comment]
Well there were some issues like this with old msgpack when I was developing.

**Comment by maxtaco** [comment]
I think travis will fetch master, so if that's what you vendored, it shouldn't matter.

**Pull request merged**
